services:
 JeelinkMqttBridge:
    image: jeelinkmqttbridge:latest
    build: 
      context: .
      dockerfile: ./dockerfile
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "8008:8000"
    volumes:
      - ./jeelink_devices.pickle:/jeelink_devices.pickle:rw
    privileged: true
    environment:
      - MQTT_BROKER_HOST=127.0.0.1
      - MQTT_BROKER_PORT=1883
      
